#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
PROG=/usr/bin/dormnet

start_service() {
    procd_open_instance
    procd_set_param command $PROG -daemon
    procd_set_param env DORMNET_ENABLE_CONSOLE=1
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall dormnet
}

service_triggers() {
    procd_add_reload_trigger dormnet
    procd_add_reload_restart
}
