#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=01

PROG=/usr/bin/dormnet

start_service() {
    procd_open_instance
    procd_set_param command $PROG -daemon
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger dormnet
}

reload_service() {
    stop
    start
}
